# Usa una imagen base de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el package.json y el package-lock.json (si está presente)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todos los archivos de la aplicación al contenedor
COPY . .

# Genera el esquema de Prisma (esto ejecutará prisma generate)
RUN npx prisma generate

# Compila el código de la aplicación
RUN npm run build

# Exponer el puerto que tu app NestJS usará
EXPOSE 4000

# Ejecuta la aplicación en modo de producción
CMD ["npm", "run", "start:prod"]
