FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el package.json y el package-lock.json (si está presente)
COPY package*.json ./


RUN npm install

# Copia todos los archivos de la aplicación al contenedor
COPY . .

# Copia el archivo schema.prisma al contenedor
COPY prisma/schema.prisma ./prisma/

# Genera el esquema de Prisma después de copiar todos los archivos
RUN npx prisma generate

RUN npm run build

# Exponer el puerto que tu app NestJS usará
EXPOSE 4000

CMD ["node", "dist/main"]