version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "start:prod"]
    networks:
      - app-network

# Si tienes una base de datos, por ejemplo PostgreSQL:
#   db:
#     image: postgres:13
#     container_name: postgres-db
#     environment:
#       POSTGRES_USER: example
#       POSTGRES_PASSWORD: example
#       POSTGRES_DB: example
#     ports:
#       - "5432:5432"
#     networks:
#       - app-network

networks:
  app-network:
    driver: bridge
