-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 10:39:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema u978018464_motorgas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u978018464_motorgas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u978018464_motorgas` DEFAULT CHARACTER SET latin1 ;
USE `u978018464_motorgas` ;

-- -----------------------------------------------------
-- Table `u978018464_motorgas`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u978018464_motorgas`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

INSERT INTO `u978018464_motorgas`.`roles` (`id`, `nombre`, `creado_en`, `actualizado_en`) VALUES
(1, 'Vendedor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Tecnico', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Administracion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- -----------------------------------------------------
-- Table `u978018464_motorgas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u978018464_motorgas`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `cover_image` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` INT(11) NOT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `nombre_usuario_2` (`nombre_usuario` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `u978018464_motorgas`.`roles` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u978018464_motorgas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u978018464_motorgas`.`clientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(200) NOT NULL,
  `dni` BIGINT(20) NOT NULL,
  `domicilio` VARCHAR(255) NULL DEFAULT NULL,
  `localidad` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` BIGINT(20) NULL DEFAULT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 78
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u978018464_motorgas`.`boletos_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u978018464_motorgas`.`boletos_reservas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `cliente_id` INT(11) NOT NULL,
  `equipo` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `reforma_escape` TINYINT(1) NULL DEFAULT '0',
  `carga_externa` TINYINT(1) NULL DEFAULT '0',
  `sena` DECIMAL(10,2) NULL DEFAULT NULL,
  `monto_final_abonar` DECIMAL(10,2) NOT NULL,
  `fecha_instalacion` DATE NOT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `marca_vehiculo` VARCHAR(100) NULL DEFAULT NULL,
  `modelo_vehiculo` VARCHAR(100) NULL DEFAULT NULL,
  `patente_vehiculo` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `boletos_reservas_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `u978018464_motorgas`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `boletos_reservas_ibfk_2`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `u978018464_motorgas`.`clientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u978018464_motorgas`.`tecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u978018464_motorgas`.`tecnica` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dia` DECIMAL(2,0) NULL DEFAULT NULL,
  `mes` DECIMAL(2,0) NULL DEFAULT NULL,
  `propietario` VARCHAR(100) NULL DEFAULT NULL,
  `dni` BIGINT(20) NULL DEFAULT NULL,
  `marca_vehiculo` VARCHAR(100) NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `patente` VARCHAR(20) NULL DEFAULT NULL,
  `observaciones_personales` TEXT NULL DEFAULT NULL,
  `observaciones_tecnicas` TEXT NULL DEFAULT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `perdidas_gas` TINYINT(1) NULL DEFAULT '0',
  `cableado` TINYINT(1) NULL DEFAULT '0',
  `nivel_agua` TINYINT(1) NULL DEFAULT '0',
  `nivel_aceite` TINYINT(1) NULL DEFAULT '0',
  `inspeccion_instalacion` TINYINT(1) NULL DEFAULT NULL,
  `funcionamiento_unidad` TINYINT(1) NULL DEFAULT '0',
  `herramientas` TINYINT(1) NULL DEFAULT NULL,
  `otras_observaciones` TEXT NULL DEFAULT NULL,
  `firma` LONGTEXT NULL DEFAULT NULL,
  `usuario_id` INT(11) NULL DEFAULT NULL,
  `comanda_id` INT(11) NOT NULL,
  `estado` ENUM('pendiente', 'completo') NULL DEFAULT NULL,
  `detalle1` VARCHAR(255) NULL DEFAULT NULL,
  `detalle2` VARCHAR(255) NULL DEFAULT NULL,
  `detalle3` VARCHAR(255) NULL DEFAULT NULL,
  `detalle4` VARCHAR(255) NULL DEFAULT NULL,
  `detalle5` VARCHAR(255) NULL DEFAULT NULL,
  `detalle6` VARCHAR(255) NULL DEFAULT NULL,
  `detalle7` VARCHAR(255) NULL DEFAULT NULL,
  `detalle8` VARCHAR(255) NULL DEFAULT NULL,
  `detalle9` VARCHAR(255) NULL DEFAULT NULL,
  `detalle10` VARCHAR(255) NULL DEFAULT NULL,
  `detalle11` VARCHAR(255) NULL DEFAULT NULL,
  `detalle12` VARCHAR(255) NULL DEFAULT NULL,
  `detalle13` VARCHAR(255) NULL DEFAULT NULL,
  `detalle14` VARCHAR(255) NULL DEFAULT NULL,
  `detalle15` VARCHAR(255) NULL DEFAULT NULL,
  `detalle16` VARCHAR(255) NULL DEFAULT NULL,
  `detalle17` VARCHAR(255) NULL DEFAULT NULL,
  `detalle18` VARCHAR(255) NULL DEFAULT NULL,
  `detalle19` VARCHAR(255) NULL DEFAULT NULL,
  `detalle20` VARCHAR(255) NULL DEFAULT NULL,
  `kilometros` VARCHAR(255) NULL DEFAULT NULL,
  `firma_tecnico` LONGTEXT NULL DEFAULT NULL,
  `perdidas_gas_adicional` VARCHAR(255) NULL DEFAULT NULL,
  `cableado_adicional` VARCHAR(255) NULL DEFAULT NULL,
  `nivel_agua_adicional` VARCHAR(255) NULL DEFAULT NULL,
  `nivel_aceite_adicional` VARCHAR(255) NULL DEFAULT NULL,
  `inspeccion_instalacion_adicional` VARCHAR(255) NULL DEFAULT NULL,
  `funcionamiento_unidad_adicional` VARCHAR(255) NULL DEFAULT NULL,
  `herramientas_adicional` VARCHAR(255) NULL DEFAULT NULL,
  `falla_encendido` TINYINT(1) NULL DEFAULT '0',
  `luz_check` TINYINT(1) NULL DEFAULT '0',
  `vehiculo_fuera_punto` TINYINT(1) NULL DEFAULT '0',
  `arreglo_reciente` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_comanda_id` (`comanda_id` ASC) VISIBLE,
  INDEX `idx_usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tecnica_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `u978018464_motorgas`.`comandas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tecnica_ibfk_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `u978018464_motorgas`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u978018464_motorgas`.`comandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u978018464_motorgas`.`comandas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boleto_reserva_id` INT(11) NOT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('pendiente', 'en_proceso', 'completado') NULL DEFAULT 'pendiente',
  `reductor_cod` VARCHAR(100) NULL DEFAULT NULL,
  `reductor_numero` VARCHAR(100) NULL DEFAULT NULL,
  `cilindro_1_cod` VARCHAR(100) NULL DEFAULT NULL,
  `cilindro_1_numero` VARCHAR(100) NULL DEFAULT NULL,
  `valvula_1_cod` VARCHAR(100) NULL DEFAULT NULL,
  `valvula_1_numero` VARCHAR(100) NULL DEFAULT NULL,
  `reforma_escape_texto` TEXT NULL DEFAULT NULL,
  `carga_externa` TINYINT(1) NULL DEFAULT '0',
  `precio_carga_externa` VARCHAR(255) NULL DEFAULT NULL,
  `cilindro_2_cod` VARCHAR(100) NULL DEFAULT NULL,
  `cilindro_2_numero` VARCHAR(100) NULL DEFAULT NULL,
  `valvula_2_cod` VARCHAR(100) NULL DEFAULT NULL,
  `valvula_2_numero` VARCHAR(100) NULL DEFAULT NULL,
  `cuna` VARCHAR(255) NULL DEFAULT NULL,
  `materiales` TEXT NULL DEFAULT NULL,
  `tecnica_id` INT(11) NULL DEFAULT NULL,
  `cilindro_3_cod` VARCHAR(100) NULL DEFAULT NULL,
  `cilindro_3_numero` VARCHAR(100) NULL DEFAULT NULL,
  `valvula_3_cod` VARCHAR(100) NULL DEFAULT NULL,
  `valvula_3_numero` VARCHAR(100) NULL DEFAULT NULL,
  `cilindro_4_cod` VARCHAR(100) NULL DEFAULT NULL,
  `cilindro_4_numero` VARCHAR(100) NULL DEFAULT NULL,
  `valvula_4_cod` VARCHAR(100) NULL DEFAULT NULL,
  `valvula_4_numero` VARCHAR(100) NULL DEFAULT NULL,
  `pagos_efectivo_transferencia` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_tarjeta_1` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_plan_tarjeta_1` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_tarjeta_2` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_plan_tarjeta_2` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_tarjeta_3` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_plan_tarjeta_3` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_tarjeta_4` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_plan_tarjeta_4` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_tarjeta_5` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_plan_tarjeta_5` VARCHAR(255) NULL DEFAULT NULL,
  `pagos_dolares` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `boleto_reserva_id` (`boleto_reserva_id` ASC) VISIBLE,
  INDEX `tecnica_id` (`tecnica_id` ASC) VISIBLE,
  CONSTRAINT `comandas_ibfk_1`
    FOREIGN KEY (`boleto_reserva_id`)
    REFERENCES `u978018464_motorgas`.`boletos_reservas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `comandas_ibfk_2`
    FOREIGN KEY (`tecnica_id`)
    REFERENCES `u978018464_motorgas`.`tecnica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u978018464_motorgas`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u978018464_motorgas`.`archivo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  `comanda_id` INT(11) NOT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `archivo_comanda_id_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `archivo_comanda_fk`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `u978018464_motorgas`.`comandas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u978018464_motorgas`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u978018464_motorgas`.`calendario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `boleto_reserva_id` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'confirmado', 'completado', 'cancelado', 'no_presentado') NULL DEFAULT 'pendiente',
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_boleto_reserva_id` (`boleto_reserva_id` ASC) VISIBLE,
  CONSTRAINT `fk_boleto_reserva_id`
    FOREIGN KEY (`boleto_reserva_id`)
    REFERENCES `u978018464_motorgas`.`boletos_reservas` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
